### ISSUE TITLE
Is it possible to remove "Hello-world" folder?

### ISSUE THREAD

**Issue by agomezru** [hawkeye2013/angular-rust-electron#3]
This one is an incredible boilerplate. It saved my life. So, I'm really thankful.

This isn't really an Issue.
I was wondering if it's possible to compile the project without the "Hello-world" folder.

I tried to do it, but I can't run it after that. 

Thanks in advance!

**Comment by tuckers-tech** [comment]
Hi @agomezru!  Glad the boilerplate is useful for you!  I just tried it myself and you're right!  It built fine in development but failed when building for prod without the `hello-world/` folder.  How bizarre...  Is yours failing in just prod as well?

I'll take a look at it sometime in the next couple of days to see if I can find the root cause of it.  Thank you for bringing it up!

**Comment by agomezru** [comment]
Thanks for your answer @hawkeye2013 

It is like that, yes. 
It's working with `npm start`
It is failing with `npm run electron:build`

It seems an issue with dist-exe folder. It's not recreating that folder at `npm run electron:build `

Thanks!

**Comment by tuckers-tech** [comment]
Hi @agomezru.  Sorry it took me more than a couple of days to look at this!  

I think I found the problem.  I believe I was trying to create a child folder before the parent folder existed.  That folder was being created when the executables built with cargo were added, but not with neon.  I'll push up a change in the next couple of minutes, as long as I don't see any issues with it.  Thank you again for bringing this up!

**Comment by agomezru** [comment]
> Hi @agomezru. Sorry it took me more than a couple of days to look at this!
> 
> I think I found the problem. I believe I was trying to create a child folder before the parent folder existed. That folder was being created when the executables built with cargo were added, but not with neon. I'll push up a change in the next couple of minutes, as long as I don't see any issues with it. Thank you again for bringing this up!

That's great. It's working like a charm. 
Thanks for taking your time to solve it.
